version: "3"

services:
  plumfish:
    image: revezo/plumfish:0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plumfish
    ports:
      - 8080:8080
      - 15005:5005
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/plumfish_db
      SPRING_DATASOURCE_USERNAME: plumfish
      SPRING_DATASOURCE_PASSWORD: plumfish
      SPRING_RABBITMQ_ADDRESSES: rabbitmq:5672
      MODULES_TWITTER_AUTHENTICATION_CONSUMER-KEY: ${TWITTER_CONSUMER_KEY}
      MODULES_TWITTER_AUTHENTICATION_CONSUMER-SECRET: ${TWITTER_CONSUMER_SECRET}
      MODULES_TWITTER_AUTHENTICATION_TOKEN: ${TWITTER_TOKEN}
      MODULES_TWITTER_AUTHENTICATION_TOKEN-SECRET: ${TWITTER_TOKEN_SECRET}
      MODULES_RAFFLE_RANDOMAPIKEY: ${RANDOM_API_KEY}
      MODULES_RAFFLE_DRAWPACKAGESCHEDULER_DELAY: ${RAFFLE_SCHEDULER_DELAY}
      SPRING_MAIL_HOST: ${MAIL_HOST}
      SPRING_MAIL_PORT: ${MAIL_PORT}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      MODULES_MAIL_ADMINS: ${ADMIN_EMAILS}
    entrypoint: ["java", "-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n", "-jar","/app.jar"]
    depends_on:
      - mysql
      - rabbitmq
    restart: on-failure:10
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plumfish_db
      MYSQL_USER: plumfish
      MYSQL_PASSWORD: plumfish
    ports:
      - 3306:3306
    restart: on-failure:10
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 15672:15672 #management console
      - 5672:5672