spring:
  profiles:
    active: dev
  application:
    name: plumfish
  liquibase:
    change-log: classpath:/db/changelog-master.yml
  rabbitmq:
    username: admin
    password: admin
    addresses: rabbitmq:5672
logging:
  level:
    "liquibase" : info
modules:
  publisher:
    twitter-authentication:
        consumerKey: consumerKey
        consumerSecret: consumerSecret
        token: token
        tokenSecret: tokenSecret
---
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/plumfish_db
    username: plumfish
    password: plumfish
  rabbitmq:
    addresses: rabbitmq:5672
  config:
    activate:
      on-profile: docker
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plumfish_db
    username: plumfish
    password: plumfish
  rabbitmq:
    addresses: localhost:5672
  config:
    activate:
      on-profile: dev